package main

import "cmd/main.go/pkg/matriz"

// Main GO
func main() {
	// fmt.Println()
	// fmt.Printf("[My-Pkg] Call my pkg: %d\n", soma.Soma(1, 2))
	// fmt.Println()
	// vars.Variaveis()
	// fmt.Println()
	// consts.Constantes()
	// fmt.Println()
	// loop.Loop()
	// fmt.Println()
	// ifelse.Ifelse()
	// fmt.Println()
	// switchcase.Switch()
	// fmt.Println()
	// cleanReurn.UseSplit()
	// fmt.Println()
	// castOrwrapper.Cast()
	// fmt.Println()
	// watchType.WatchType()
	// fmt.Println()
	// consts.ConstantesNumericas()
	// fmt.Println()
	// deferFunc.Defer()
	// fmt.Println()
	// ponteiros.Ponteiros()
	// fmt.Println()
	// structs.Structs()
	// fmt.Println()
	// functions.Main()
	// fmt.Println()
	matriz.Matriz()
	// fmt.Println()
	// make.Make()
	// fmt.Println()
	// maps.Maps()
	// fmt.Println()
	// exercicios.Maps()
	// fmt.Println()
	// exercicios.Fibonacci()
	// fmt.Println()
	// exercicios.Errors()
	// fmt.Println()
	// interfaces.Main()
	// fmt.Println()
	// stringers.Main()
	// fmt.Println()
	// errors.Errors()
	// concurrency.Main()
	// fmt.Println()
}
